# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulefile',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
