# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0002_auto_20180216_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulefile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
