# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0003_auto_20180216_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulefile',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='schedulefile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c904e28-1369-11e8-bd5d-20c9d08bb53f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
