# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0004_auto_20180216_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replaces', models.DateField()),
                ('replaced_with', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('term_begins', models.DateField()),
                ('term_ends', models.DateField()),
                ('holidays_begin', models.DateField()),
                ('holidays_end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedulefile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac3a23f4-13fb-11e8-939d-20c9d08bb53f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='switchedday',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switched_days', to='web_client.Term'),
        ),
    ]
