# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0005_auto_20180217_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulefile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be47741e-13fb-11e8-aac4-20c9d08bb53f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
