# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0008_auto_20180218_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawcsvevent',
            old_name='module',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='schedulefile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adf0a586-1446-11e8-88a7-20c9d08bb53f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
