# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0010_auto_20180218_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawcsvevent',
            old_name='weeks',
            new_name='semester_weeks',
        ),
        migrations.AlterField(
            model_name='schedulefile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9000f9ac-144d-11e8-aebd-20c9d08bb53f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
